version: "3.7"

services:

  db:
    container_name: postgresql_db
    image: postgres:10-alpine
    restart: always
    ports:
      - 5490:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  api:
    container_name: api
    build: .
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db